// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi3dUICZOwmfo775-vFgnWWx9NnenVsio',
    appId: '1:117410744135:web:4bd6aa00253e06bd3eae62',
    messagingSenderId: '117410744135',
    projectId: 'spamexposezzz',
    authDomain: 'spamexposezzz.firebaseapp.com',
    storageBucket: 'spamexposezzz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlptb_fVR13yt3X98er8CYaalkuK8VXV0',
    appId: '1:117410744135:android:d03969287a52cd353eae62',
    messagingSenderId: '117410744135',
    projectId: 'spamexposezzz',
    storageBucket: 'spamexposezzz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCabsyKedRBV3JihsjHyACWaWoqwU8DC0',
    appId: '1:117410744135:ios:2af004721f9e45a13eae62',
    messagingSenderId: '117410744135',
    projectId: 'spamexposezzz',
    storageBucket: 'spamexposezzz.appspot.com',
    iosBundleId: 'com.example.spamexposeapp',
  );
}
